SHELL := /bin/bash

.PHONY: install dev build start test lint migrate seed

init-install:
	npm i

install:
	npm ci

deV:
	npm run dev

build:
	npm run build

start:
	npm run start

lint:
	npm run lint

test:
	npm run test


# Add migrate/seed targets later when Prisma/SQL is wired.